### ISSUE TITLE
AttributeError: 'valve' object has no attribute 'fk_nominal_diameter__REL'

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#51]
https://github.com/QGEP/qgepqwat2ili/blob/bc0f3f429734f6b2e45603fe28d0b63cb2221ab7/qgepqwat2ili/qwat/export.py#L712

nominal_diameter is a regular TEXT*10 attribute
I cannot find a related value table in qwat_sys.

![qwat valve_nominal_diameter_errorjpg](https://user-images.githubusercontent.com/1265865/132579689-a3845865-1e32-4d1a-b09a-0e0fd71660dc.jpg)
![qwat valve_nominal_diameter_data](https://user-images.githubusercontent.com/1265865/132579692-22321762-2602-43c5-8b56-900846557c34.jpg)

Nennweite is not MANDATORY in SIA405 water
`  Nennweite: TEXT*10;  !! als TEXT, da zum Teil auch Doppelwerte mit Schrägstrich (z.B. 1500/800);`

So not clear, why this fails - empty or NULL values should be allowed.

**Comment by olivierdalang** [comment]
Are you using an old version of QWAT ?

The tool is only expected to work with an updated QWAT (1.3.6).  `nominal_diameter` was added in QWAT 1.3.4. You should have a `qwat_vl.nominal_diameter` table as well as the `fk_nominal_diameter` column on the valve tables.

I'll close this, please reopen if you're already using QWAT 1.3.6 in which case it's a more serious issue.

Also opened a new issue about clarifying which versions are supported here : https://github.com/QGEP/qgepqwat2ili/issues/53
